version: 2
updates:
  # Maintain dependencies for go-modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/zclconf/go-cty"
        versions: ["1.x"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
